name: Rclone

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  rclone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Configure Rclone
        run: |
          wget -qq '${{ secrets.RCLONE_CONFIG }}'
          ls
      - name: Run Rclone job
        run: |
            rclone --config rclone.conf move NewBlaze:Spidy717 OneDrive:Drive2/OnlyPicture --include "*.{jpg,png,jpeg,gif,webp}" --transfers 20 -P
